import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { uploadToR2FromUrl } from "@/lib/r2";

// Leonardo.ai Config
const LEONARDO_API_KEY = process.env.LEONARDO_API_KEY;
const MODEL_ID = "1dd50843-d653-4516-a8e3-f0238ee453ff"; // FLUX Schnell

export const maxDuration = 60; // Allow up to 1 minute for AI generation

export async function GET(req: Request) {
  try {
    // 1. Security Check (Optional but recommended)
    const { searchParams } = new URL(req.url);
    const key = searchParams.get("key");
    if (key !== process.env.AUTH_SECRET && process.env.NODE_ENV === "production") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // 2. Pick a random Bot User
    const bots = await prisma.user.findMany({
      where: { email: { startsWith: "bot_" } },
      select: { id: true }
    });
    const botId = bots[Math.floor(Math.random() * bots.length)]?.id;
    if (!botId) throw new Error("No bots found");

    // 3. Pick a Category that needs images
    const categories = await prisma.category.findMany({
        include: { _count: { select: { images: true } } }
    });

    // Prioritize categories with 0 images, then fewer than 10
    const pendingCategories = categories.filter(c => c._count.images < 10);
    const category = pendingCategories[Math.floor(Math.random() * pendingCategories.length)] || categories[0];

    // 4. Create Smart Prompt
    let style = "photograph";
    if (category.slug.match(/art|draw|sketch|illustration|fantasy|logo/)) style = "artwork";

    let prompt = `stunning high quality ${category.name} ${style} with perfect composition and lighting, professional visual, highly detailed`;
    if (category.slug.includes("logo")) {
        prompt = `minimalist professional ${category.name} logo, vector art, clean lines, white background, no text, no words`;
    }

    console.log(`🤖 Generating for category: ${category.name} using prompt: ${prompt}`);

    // 5. Call Leonardo.ai
    const genRes = await fetch("https://cloud.leonardo.ai/api/rest/v1/generations", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${LEONARDO_API_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        prompt,
        modelId: MODEL_ID,
        width: 736,
        height: 1104,
        num_images: 1,
      })
    });

    const genData = await genRes.json();
    const generationId = genData.sdGenerationJob?.generationId;
    if (!generationId) throw new Error("Failed to start generation");

    // 6. Poll for Result (simple wait for 20s for FLUX Schnell)
    await new Promise(r => setTimeout(r, 20000));

    const statusRes = await fetch(`https://cloud.leonardo.ai/api/rest/v1/generations/${generationId}`, {
      headers: { "Authorization": `Bearer ${LEONARDO_API_KEY}` }
    });
    const statusData = await statusRes.json();
    const imageUrl = statusData.generations_by_pk?.generated_images[0]?.url;

    if (!imageUrl) throw new Error("Image not ready or failed");

    // 7. Upload to R2
    const filename = `${category.slug}-${Date.now()}.jpg`;
    const publicUrl = await uploadToR2FromUrl(imageUrl, `images/ai/${filename}`);

    // 8. Save to DB
    const newImage = await prisma.image.create({
      data: {
        title: `${category.name} Inspiration`,
        description: `A beautiful ${category.name} visual generated by Pinsora AI.`,
        imageUrl: publicUrl,
        categoryId: category.id,
        userId: botId,
        isPublished: true,
      }
    });

    return NextResponse.json({ success: true, imageId: newImage.id });

  } catch (error: any) {
    console.error("CRON ERROR:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
