import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function POST(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { imageUrl, prompt } = await req.json();

    // نجد فئة "Abstract" أو أي فئة عامة لحفظ صورة المستخدم فيها
    const category = await prisma.category.findFirst({
      where: { slug: "abstract" }
    }) || await prisma.category.findFirst();

    const image = await prisma.image.create({
      data: {
        title: "AI Generation",
        description: prompt || "Generated by Pinsora AI",
        imageUrl: imageUrl,
        userId: session.user.id,
        categoryId: category?.id || "",
        isPublished: true,
      },
    });

    return NextResponse.json({ success: true, image });
  } catch (error) {
    console.error("Save Image Error:", error);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
