name: Pinsora Image Factory 🏭

on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
  workflow_dispatch:      # Allows manual trigger from GitHub UI

jobs:
  ping-generator:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Site to Generate Image
        run: |
          curl -L "https://pinsora.vercel.app/api/cron/generate?key=${{ secrets.CRON_SECRET }}"
